import pandas as pd
import numpy as np
import yfinance as yf

from Data.Database import (
    session,
    create_tables,
    Company,
    MarketData,
    Financials
)

from Data.Importing import (
    download_share_data,
    store_share_data,
    store_fin_data,
    import_fin_data,
    store_fin_data
)

from merton_model import MertonModel

create_tables()
ticker="GOOG"

# google = Company(
#     ticker="GOOG",
#     sector="Technology",
#     company_name="Alphabet Inc."
# )

# session.add(google)
# session.commit()

# Testing code generated by chatgpt
try:

    # 1. Import one year of SEC data
    data = import_fin_data(
        ticker=ticker,
        start_year=2025,
        end_year=2025
    )

    print("\n=== IMPORTED DATA ===")
    print(data)

    # 2. Store the data in SQL database
    store_fin_data(
        data=data,
        ticker=ticker,
        session=session
    )

    # 3. Query the database
    results = (
        session.query(Financials)
        .join(Financials.company)
        .filter(Financials.company.has(ticker=ticker))
        .order_by(Financials.filing_date)
        .all()
    )

    print("\n=== DATABASE RESULTS ===")

    for row in results:
        print(
            row.filing_date,
            row.period_end,
            row.fiscal_year,
            row.fiscal_period,
            row.total_assets,
            row.total_debt,
            row.ordinary_shares
        )

finally:
    session.close()

